services:
  shame_bot:
    build: .
    image: shame_bot:latest
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - APPLICATION_ID=${APPLICATION_ID}
      - PUBLIC_KEY=${PUBLIC_KEY}
      - DATABASE_URL=${DATABASE_URL}
